version: "3.7"
services:
# ---
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - cel_intel_network
# ---
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - .:/api_data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: database
    depends_on:
      - database
    networks:
      - cel_intel_network
# ---
  dashboard:
    container_name: dashboard
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/dashboard_data
    environment:
      API_ENDPOINT: http://api:8000/
    depends_on:
      - api
    networks:
      - cel_intel_network
# ---
volumes:
  database_data:
  api_data:
  dashboard_data:
# ---
networks:
  cel_intel_network:
    driver: bridge