apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  POSTGRES_HOST: cel-db-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  API_ENDPOINT: cel-api-service