apiVersion: v1
kind: Service
metadata:
  name: cel-db-service
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cel-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cel-db
spec:
  serviceName: cel-db
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        name: cel-db   # Add a name to the pod
    spec:
      containers:
      - name: postgresql
        image: frogdance/cel-db:lastest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: cel-db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: cel-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
